---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cuatimar/public_html/
    - /bin/cp -R index.php $DEPLOYPATH
    - /bin/cp -R aviso_priv.html $DEPLOYPATH
    - export DEPLOYPATH = /home/cuatimar/public_html/css
    - /bin/cp -R stylesheet.css $DEPLOYPATH
    - /bin/cp -R styles.css $DEPLOYPATH
    - /bin/cp -R new.css $DEPLOYPATH
    - export DEPLOYPATH = /home/cuatimar/public_html/js
    - /bin/cp -R app.js $DEPLOYPATH
    - /bin/cp -R new_app.js $DEPLOYPATH
    - export DEPLOYPATH = /home/cuatimar/public_html/partials
    - /bin/cp -R footer.php $DEPLOYPATH
    - /bin/cp -R header.php $DEPLOYPATH